parameters:
    loader.debug: false
    loader.environment: '%env(APP_ENV)%'
    loader.enable_aggregation: false
    
    # Loader colors
    loader.colors: {}

    loader.usages.responsive:
      list:
        xs:
          allow_switch: true
          breakpoint: 0
        s:
          allow_switch: true
          breakpoint: 576
        m:
          allow_switch: true
          breakpoint: 768
        l:
          allow_switch: true
          breakpoint: 992
        xl:
          allow_switch: true
          breakpoint: 1200
        xxl:
          allow_switch: true
          breakpoint: 1400

    # Color schemes
    loader.usages.color_scheme:
      default: default
      list:
        dark:
          allow_switch: false
        default:
          allow_switch: false
        light:
          allow_switch: false

    # Margins
    loader.usages.margins:
      default: default
      list:
        default:
          allow_switch: false
        fat:
          allow_switch: false
        slim:
          allow_switch: false
        none:
          allow_switch: false

    # Animations
    loader.usages.animations:
      default: none
      list:
        bounce:
          allow_switch: false
        none:
          allow_switch: false
        soft:
          allow_switch: false

    # Fonts
    loader.usages.fonts:
      default: none
      list:
        none:
          allow_switch: false
        demo:
          allow_switch: false

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyLoader\Rendering\ComponentManager\:
        resource: '../../Rendering/ComponentManager/*'
        tags:
            - { name: 'symfony_loader.component_manager' }

    Wexample\SymfonyLoader\Rendering\ComponentManagerLocatorService:
        arguments: [!tagged_locator { tag: 'symfony_loader.component_manager' }]

    Wexample\SymfonyLoader\:
        resource: '../../{Command,Controller,EventSubscriber,Service,Twig}'
        tags: ['controller.service_arguments']

    Wexample\SymfonyLoader\Controller\Pages\DemoController:
        tags:
            - { name: 'has_simple_routes' }

    Wexample\SymfonyLoader\Controller\Config\TestController:
        tags:
            - { name: 'has_simple_routes' }

    Wexample\SymfonyLoader\Twig\ColorExtension:
        arguments:
            $colors: '%loader.colors%'
